---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shawn.
--- DateTime: 2026/3/30 20:28
---

local zsetKey = KEYS[1] -- 操作的 Key
local membersScores = ARGV -- 获取传入的成员和分数列表
local sizeLimit = 500 -- ZSet 最多缓存 500 条评论

-- 检查 ZSet 是否存在
if redis.call('EXISTS', zsetKey) == 0 then
    return -1
end

local currentSize = redis.call('ZCARD', zsetKey)

-- 遍历传入的成员和分数，添加到 ZSet 中
for i = 1, #membersScores, 2 do
    local member = membersScores[i] -- 评论 ID
    local score = membersScores[i + 1] -- 热度值
    if currentSize < sizeLimit then
        redis.call('ZADD', zsetKey, score, member)
        currentSize = currentSize + 1
    else
        break -- 否则，则达到最大限制，停止添加
    end
end

return 0