---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shawn.
--- DateTime: 2025/12/28 12:22
---

local key = KEYS[1]

-- 创建一个空表来存储批量添加的数据
local zaddArgs = {}

for i = 1, #ARGV - 1, 2 do
    table.insert(zaddArgs, ARGV[i]) -- 分数（关注时间戳）
    table.insert(zaddArgs, ARGV[i + 1]) -- 值（关注的用户ID）
end

-- 调用 ZADD 批量插入数据
redis.call('ZADD', key, unpack(zaddArgs))

local expireTime = ARGV[#ARGV]  -- 最后一个参数为过期时间
redis.call('EXPIRE', key, expireTime)

return 0