---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shawn.
--- DateTime: 2025/12/28 12:14
---

local key = KEYS[1]
local followUserId = ARGV[1]
local timestamp = ARGV[2]
local expireSeconds = ARGV[3]

redis.call('ZADD', key, timestamp, followUserId)
redis.call('EXPIRE', key, expireSeconds)
return 0