---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shawn.
--- DateTime: 2026/1/3 16:46
---
--- 校验关注列表是否存在并移除关注关系

local key = KEYS[1]
local unfollowUserId = ARGV[1]

local exists = redis.call('EXISTS', key)
if exists == 0 then
    return -1
end

local score = redis.call('ZSCORE', key, unfollowUserId)
if score == false or score == nil then
    return -4
end

redis.call('ZREM',key,unfollowUserId)
return 0