---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shawn.
--- DateTime: 2026/1/13 21:28
---

local key = KEYS[1]

for i = 1, #ARGV - 1 do
    redis.call('BF.ADD', key, ARGV[i])
end

-- 最后一个参数为过期时间
local expireTime = ARGV[#ARGV]
redis.call('EXPIRE', key, expireTime)
return 0