---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Summer Snow.
--- DateTime: 2026/1/18 18:44
---

local key=KEYS[1]
local noteId=ARGV[1]

local exists=redis.call('EXISTS',key)
if(exists==0) then
    return -1
end

return redis.call('BF.EXISTS',key,noteId)