---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shawn.
--- DateTime: 2026/1/20 21:27
---

local key = KEYS[1]
local noteId = ARGV[1]

local exists = redis.call('EXISTS', key)
if exists == 0 then
    return -1
end

local isCollected = redis.call('BF.EXISTS', key, noteId)
if isCollected == 1 then
    return 1
end

-- 未被收藏，添加收藏数据
redis.call('BF.ADD', key, noteId)