---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Summer Snow.
--- DateTime: 2026/1/22 19:20
---

local key = KEYS[1]
local noteId = ARGV[1]
local expireSeconds = ARGV[2]

redis.call("BF.ADD", key, noteId);

redis.call("EXPIRE", key, expireSeconds)
return 0