---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shawn.
--- DateTime: 2026/1/22 21:27
---

local key = KEYS[1]
local noteId = ARGV[1]
local type = tonumber(ARGV[2]) -- 0：取消收藏 1：收藏



local exists = redis.call('EXISTS', key)
if exists == 0 then
    return -1
end

if type == 1 then
    local timestamp = ARGV[3]
    local size = redis.call('ZCARD', key)
    if (size >= 300) then
        redis.call('ZPOPMIN', key)
    end
    redis.call('ZADD', key, timestamp, noteId)
elseif type == 0 then
    redis.call('ZREM', key, noteId)
end