---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Summer Snow.
--- DateTime: 2026/2/2 20:02
---

local key = KEYS[1]
local noteIdOrNoteCreatorId = ARGV[1]

local exists = redis.call('EXISTS', key)
if exists == 0 then
    redis.call('BF.ADD', key, '')
    redis.call('EXPIRE', key, 24 * 60 * 60)
end

return redis.call('BF.EXISTS', key, noteIdOrNoteCreatorId)