---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Summer Snow.
--- DateTime: 2026/2/4 20:09
---

local key = KEYS[1]
local userId = ARGV[1]

local exists = redis.call('EXISTS', key)
if exists == 0 then
    redis.call('BF.ADD', key, '')
    redis.call('EXPIRE', key, 24 * 60 * 60)
end

return redis.call('BF.ADD', key, userId)