---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Shawn.
--- DateTime: 2026/1/31 22:16
---

local key = KEYS[1]
local noteIdOrNoteCreatorId = ARGV[1]

local exists = redis.call('EXISTS', key)

if exists == 0 then
    -- 创建布隆过滤器
    redis.call('BF.ADD', key, '')
    redis.call('EXPIRE', key, 24 * 60 * 60)
end

-- 校验该变更数据是否已经存在(1 表示已存在，0 表示不存在)
return redis.call('BF.EXISTS', key, noteIdOrNoteCreatorId)